services:
  ng-bootstrap-demo:
    image: ghcr.io/mintplayer/mintplayer-ng-bootstrap:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ng-bootstrap-demo.rule=Host(`bootstrap.mintplayer.com`)"
      - "traefik.http.routers.ng-bootstrap-demo.entrypoints=websecure"
      - "traefik.http.routers.ng-bootstrap-demo.tls.certresolver=letsencrypt"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
