services:
  ng-bootstrap:
    image: ghcr.io/mintplayer/mintplayer-ng-bootstrap:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ng-bootstrap.rule=Host(`bootstrap.mintplayer.com`)"
      - "traefik.http.routers.ng-bootstrap.entrypoints=websecure"
      - "traefik.http.routers.ng-bootstrap.tls.certresolver=letsencrypt"
    networks:
      - web
    restart: unless-stopped

  react-bootstrap-demo:
    image: ghcr.io/mintplayer/mintplayer-ng-bootstrap-react-demo:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-bootstrap-demo.rule=Host(`react.bootstrap.mintplayer.com`)"
      - "traefik.http.routers.react-bootstrap-demo.entrypoints=websecure"
      - "traefik.http.routers.react-bootstrap-demo.tls.certresolver=letsencrypt"
      - "traefik.http.services.react-bootstrap-demo.loadbalancer.server.port=80"
    networks:
      - web
    restart: unless-stopped

  vue-bootstrap-demo:
    image: ghcr.io/mintplayer/mintplayer-ng-bootstrap-vue-demo:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vue-bootstrap-demo.rule=Host(`vue.bootstrap.mintplayer.com`)"
      - "traefik.http.routers.vue-bootstrap-demo.entrypoints=websecure"
      - "traefik.http.routers.vue-bootstrap-demo.tls.certresolver=letsencrypt"
      - "traefik.http.services.vue-bootstrap-demo.loadbalancer.server.port=80"
    networks:
      - web
    restart: unless-stopped

  api:
    image: ghcr.io/mintplayer/mintplayer-ng-bootstrap-api:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ng-bootstrap-api.rule=Host(`api.bootstrap.mintplayer.com`)"
      - "traefik.http.routers.ng-bootstrap-api.entrypoints=websecure"
      - "traefik.http.routers.ng-bootstrap-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.ng-bootstrap-api.loadbalancer.server.port=8080"
    volumes:
      - api-data:/data
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true

volumes:
  api-data:
