import { Routes } from '@angular/router';

export const ROUTES: Routes = [
  { path: '', loadChildren: () => [], pathMatch: 'full', canActivate: [() => false] },
  { path: 'calendar', loadComponent: () => import('./calendar/calendar.component').then(m => m.CalendarComponent) },
  { path: 'alert', loadComponent: () => import('./alert/alert.component').then(m => m.AlertComponent) },
  { path: 'forms', loadChildren: () => import('./forms/forms.routes').then(m => m.ROUTES) },
  { path: 'carousel', loadComponent: () => import('./carousel/carousel.component').then(m => m.CarouselComponent) },
  { path: 'datepicker', loadComponent: () => import('./datepicker/datepicker.component').then(m => m.DatepickerComponent) },
  { path: 'color-picker', loadComponent: () => import('./color-picker/color-picker.component').then(m => m.ColorPickerComponent) },
  { path: 'rating', loadComponent: () => import('./rating/rating.component').then(m => m.RatingComponent) },
  { path: 'progress-bar', loadComponent: () => import('./progress-bar/progress-bar.component').then(m => m.ProgressBarComponent) },
  { path: 'list-group', loadComponent: () => import('./list-group/list-group.component').then(m => m.ListGroupComponent) },
  { path: 'for-directive', loadComponent: () => import('./for-directive/for-directive.component').then(m => m.ForDirectiveComponent) },
  { path: 'timepicker', loadComponent: () => import('./timepicker/timepicker.component').then(m => m.TimepickerComponent) },
  { path: 'button-group', loadComponent: () => import('./button-group/button-group.component').then(m => m.ButtonGroupComponent) },
  { path: 'blockquote', loadComponent: () => import('./blockquote/blockquote.component').then(m => m.BlockquoteComponent) },
  { path: 'breadcrumb', loadComponent: () => import('./breadcrumb/breadcrumb.component').then(m => m.BreadcrumbComponent) },
  { path: 'badge', loadComponent: () => import('./badge/badge.component').then(m => m.BadgeComponent) },
  { path: 'close', loadComponent: () => import('./close/close.component').then(m => m.CloseComponent) },
  { path: 'spinner', loadComponent: () => import('./spinner/spinner.component').then(m => m.SpinnerComponent) },
  { path: 'placeholder', loadComponent: () => import('./placeholder/placeholder.component').then(m => m.PlaceholderComponent) },
  { path: 'pagination', loadComponent: () => import('./pagination/pagination.component').then(m => m.PaginationComponent) },
  { path: 'table', loadComponent: () => import('./table/table.component').then(m => m.TableComponent) },
  { path: 'button-type', loadComponent: () => import('./button-type/button-type.component').then(m => m.ButtonTypeComponent) },
  { path: 'containers', loadChildren: () => import('./containers/containers.routes').then(m => m.ROUTES) },
  { path: 'treeview', loadComponent: () => import('./treeview/treeview.component').then(m => m.TreeviewComponent) },
  { path: 'marquee', loadComponent: () => import('./marquee/marquee.component').then(m => m.MarqueeComponent) },
  { path: 'icon', loadComponent: () => import('./icon/icon.component').then(m => m.IconComponent) },
];
